# SPDX-FileCopyrightText: 2022-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rasa-model-server.fullname" . }}
  labels:
    app: {{ template "rasa-model-server.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "rasa-model-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    name: {{ template "rasa-model-server.fullname" . }}
  ports:
  - name: models
    port: 8080
