# Copyright 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

global:
  image:
    registry: ""
    tag: ""

image:
  registry: "registry.aetherproject.org"
  repository: aether-apps/network-diag-app
  pullPolicy: Always
  tag: "{{ .Chart.AppVersion }}"

service:
  name: network-diag-app
  type: ClusterIP
  port: 3333
