# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

nameOverride: ""
fullnameOverride: "chronos-exporter"

replicaCount: 1
annotations: {}

image:
  repository: onosproject/chronos-exporter
  tag: v0.0.18
  pullPolicy: IfNotPresent
  pullSecrets: []

service:
  type: ClusterIP

configfile: /etc/chronos-exporter/configs/demo-configuration.yaml
aetherfile: /etc/chronos-exporter/configs/MEGA_Patch_2.0.yaml
alertfile: /etc/chronos-exporter/alerts/demo-alert.yaml
